language: vim

before_script: |
    git clone https://github.com/junegunn/vader.vim.git

script: |
    cd test &&
    vim -Nu <(cat << VIMRC
    filetype off
    set rtp+=vader.vim
    set rtp+=.
    filetype plugin indent on
    syntax enable
    VIMRC) -c 'Vader!*' > /dev/null
